name: Build and push Docker image

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITH_TOKEN }}
          image-name: zsbwebsite
          dockerfile: Dockerfile
